/*
 * Rescue the Div-Soup Page — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html (the Jasmine Spec Runner) and
 * check the semantic structure of the <body>. You only edit the <body>
 * of index.html — leave the <head> and the doctype exactly as they are.
 *
 * DO NOT EDIT THIS FILE. Make every spec below turn green by refactoring
 * the div-soup markup into correct semantic elements.
 *
 * Note: Jasmine draws its own results panel in the page, so we ignore
 * anything inside its reporter and only look at YOUR content.
 */

describe("Rescue the Div-Soup Page — semantic structure", function () {

  // Elements matching `sel` inside <body>, excluding Jasmine's own UI.
  function q(sel) {
    return Array.prototype.slice.call(document.querySelectorAll("body " + sel))
      .filter(function (el) {
        return !el.closest(".jasmine_html-reporter") && !el.closest('[class*="jasmine"]');
      });
  }

  it("1. the page has exactly one <header> landmark", function () {
    expect(q("header").length).toBe(1);
  });

  it("2. the page has exactly one <nav> landmark", function () {
    expect(q("nav").length).toBe(1);
  });

  it("3. the page has exactly one <main> landmark", function () {
    expect(q("main").length).toBe(1);
  });

  it("4. the page has at least one <article>", function () {
    expect(q("article").length).toBeGreaterThanOrEqual(1);
  });

  it("5. the page has exactly one <footer> landmark", function () {
    expect(q("footer").length).toBe(1);
  });

  it("6. no leftover <div> duplicates a landmark (no div.header/nav/main/article/footer)", function () {
    expect(q("div.header, div.nav, div.main, div.article, div.footer").length).toBe(0);
  });

  it("7. the interactive control is a real <button>", function () {
    expect(q("button").length).toBeGreaterThanOrEqual(1);
  });

  it("8. there is no clickable <div> pretending to be a button", function () {
    expect(q('div[onclick], div.button, div[role="button"]').length).toBe(0);
  });

  it("9. the <header> appears before the <main> (document order)", function () {
    var header = q("header")[0] || null;
    var main = q("main")[0] || null;
    expect(header).not.toBeNull();
    expect(main).not.toBeNull();
    var before = header && main &&
      (header.compareDocumentPosition(main) & Node.DOCUMENT_POSITION_FOLLOWING);
    expect(!!before).toBe(true);
  });

  it("10. the <article> sits inside the <main>", function () {
    var main = q("main")[0] || null;
    var article = q("article")[0] || null;
    expect(main).not.toBeNull();
    expect(article).not.toBeNull();
    expect(!!(main && article && main.contains(article))).toBe(true);
  });
});
